export interface RegistroConvocatoria {
  apemat: String
  apepat: String
  asignatura: String
  cDIR: String
  cPISO: String
  cPunClaModelo: String
  cPunCurriculo: String
  cPunEntPersonal: String
  cRESIDENCIA: String
  celular: String
  condicion: String
  correo: String
  curriculo: String
  dir: String
  dni: String
  dpto: String
  dsto: String
  escuela: String
  estado: Number
  exppro: String
  expuni: String
  fechaatencion: String
  fecharegistro: String
  grado: String
  lote: String
  modalidad: String
  mz: String
  nConCodigo: Number
  nTipo: String
  nombres: String
  observaciones: String
  pais: String
  piso: String
  prov: String
  residencia: String
  semestre: String
  titulo: String
  vez: Number
}
